# Generated by Django 5.1.6 on 2025-03-15 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
